ifndef $(PROJECT)

PROJECT = check-sieve

PLATFORM ?= $(shell uname -s)
ARCH ?= $(shell uname -m)

LEX = flex -I
YACC = bison -d
MAKE = make

CXX ?= clang++ -DYYDEBUG=1
CFLAGS += -I$(BASE)/gen/ -I$(BASE)/src/ -I$(BASE)/src/AST -I$(BASE)/src/Server -std=c++11 -fPIC -Wno-deprecated-register -DPLATFORM=\"$(ARCH)-$(PLATFORM)\"

ifeq ($(PLATFORM), Darwin)
CFLAGS += -mmacosx-version-min=10.9
endif

ifeq ($(PLATFORM), FreeBSD)
MAKE = gmake
endif

ifdef DEBUG
CFLAGS += -DDEBUG
endif

endif
