AST_SRC = $(BASE)/src/AST/Validation/Command.cc $(BASE)/src/AST/Validation/Test.cc $(BASE)/src/AST/Validation/Tag.cc $(BASE)/src/AST/ASTTraceVisitor.cc $(BASE)/src/AST/ASTVerificationVisitor.cc \
 $(BASE)/src/AST/ASTBlock.cc  $(BASE)/src/AST/ASTBoolean.cc  $(BASE)/src/AST/ASTBranch.cc  $(BASE)/src/AST/ASTCommand.cc  $(BASE)/src/AST/ASTCondition.cc  $(BASE)/src/AST/ASTNoOp.cc  \
 $(BASE)/src/AST/ASTNumeric.cc  $(BASE)/src/AST/ASTRequire.cc  $(BASE)/src/AST/ASTSieve.cc  $(BASE)/src/AST/ASTString.cc  $(BASE)/src/AST/ASTStringList.cc  $(BASE)/src/AST/ASTTag.cc  \
 $(BASE)/src/AST/ASTTest.cc $(BASE)/src/AST/ASTTestList.cc
AST_OBJ = $(AST_SRC:%.cc=%.o)