.TH check-sieve 1 "28 Jun 2025" "version 0.11"
.
.
.
.SH NAME
.
check-sieve - Syntax checker for mail sieves.
.
.SH SYNOPSIS
.
.B check-sieve [options]
.I file
.B [
.I file ...
.B ]
.br
.B check-sieve --help
.br
.B check-sieve --version
.
.SH DESCRIPTION
.
.B check-sieve
is a simple syntax checker for server-side mail sieves. It supports many
mail-sieve RFCs, details of which can be found below.
.
.SH OPTIONS
.
.IP "-h, --help"
Show the program help
.IP "--max-list-length N"
Check length of string lists, and flag any that are longer than the specified length
.IP "--server <host>:<port>"
Connect to the specified server, and only enable advertised capabilities
.IP "--trace-parser"
Trace the operation of the parser
.IP "--trace-scanner"
Trace the operation of the scanner
.IP "--trace-tree"
Trace the abstract-syntax-tree
.IP "--version"
Print out version information
.
.SH BUGS
.
For information on existing issues, and to file a bug report check the following URL:
https://github.com/dburkart/check-sieve/issues
.
.SH AUTHORS
.
Dana Burkart
.br
Stuart Montgomery
.
.SH SUPPORTED RFCs
.
The full list of supported RFCs is:

.RS
Sieve: An Email Filtering Language (RFC 5228)
.br
Variables Extension (RFC 5229)
.br
Date and Index Extensions (RFC 5260)
.br
Vacation Extension (RFC 5230)
.br
Include Extension (RFC 6609)
.br
Copying Without Side Effects (RFC 3894)
.br
Reject and Extended Reject Extensions (RFC 5429)
.br
Body Extension (RFC 5173)
.br
Relational Extension (RFC 5231)
.br
MIME Part Tests, Iteration, Extraction, Replacement, and Enclosure (RFC 5703)
.br
Imap4flags Extension (RFC 5232)
.br
Editheader Extension (RFC 5293)
.br
Regex Extension (DRAFT)
.br
Spamtest and Virustest Extensions (RFC 5235)
.br
Extensions for Notifications (RFC 5435)
.br
Subaddress Extension (RFC 5233)
.br
Ihave Extension (RFC 5463)
.br
Environment Extension (RFC 5183)
.br
Sieve Notification Mechanism: mailto (RFC 5436)
.br
Internet Message Access Protocol (IMAP) Events (RFC 6785)
.br
Converting Messages before Delivery (RFC 6558)
.br
Detecting Duplicate Deliveries (RFC 7352)
.br
Externally Stored Lists (RFC 6134)
.br
Delivering to Special-Use Mailboxes (RFC 8579)
.br
File Carbon Copy (FCC) (RFC 8580)
.br
Delivery by MAILBOXID (RFC 9042)
.br
Delivery Status Notifications and Deliver-By Extensions (RFC 6009)
.br
Extension for Processing Calendar Attachments (RFC 9671)
.br
Proton Expiration Extension (vendor-specific)
.br
Proton Eval Extension (vendor-specific)
.br
Dovecot Invoking External Programs (vendor-specific)
.RE
