name: C/C++ CI

on: [push]

jobs:
  ubuntu_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: make
    - name: setup test dependencies
      run: python3 -m pip install --upgrade setuptools
    - name: make test
      run: make test
